version: '3.3'

services:
  app:
    build:
      context: ../../../
      dockerfile: infra/deploy/local/Dockerfile-local
    env_file:
      - ../../../local.env
    environment:
      CHOKIDAR_USEPOLLING: "true" #enable hot-reloading
      NODE_ENV: development
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ../../../src:/app/src:ro
      - ../../../public:/app/public:ro
    networks:
      - cx-invoicing-portal

networks:
  cx-invoicing-portal: